### ISSUE TITLE
Adding expense crashes app

### ISSUE THREAD

**Issue by jubreal** [pmiddend/piggybudget#16] opened 2019-04-10 13:07 UTC
#### Expected behavior
Users should be able to be able to add expense successfully without the app crashing.

#### Actual behavior
The application closes and crashed when user add expense, if this action is repeated, the app then becomes unstable thereby rendering it totally unusable.

#### How to reproduce
1. Download and install the latest release of the app.

2. Launch the app.

3. Grant all permissions.

4. Click on the orange coloured circle with the "-" sign.

5. Insert some figures as expense value.

6. Return to the home page.

It will be observed that the app crashes and closes. Hence, the bug.
 N.B repeat steps 2-5, and the app becomes unstable after subsequent launch.
Browser: Piggy budget version 2.5
Operating system: android version 6.0

#### Recording Of The Bug
https://youtu.be/S_eYudGfMrQ

#### LOG
``` 04-10 14:09:53.954 I/am_focused_activity(949): [0,de.php_tech.piggybudget/.MainActivity]
04-10 14:09:53.967 I/am_resume_activity(949): [0,221901470,112614,de.php_tech.piggybudget/.MainActivity]
04-10 14:09:53.987 I/am_on_resume_called(4838): [0,de.php_tech.piggybudget.MainActivity]
04-10 14:10:04.192 I/am_pss  (949): [4838,10479,de.php_tech.piggybudget,120679424,118395904]
04-10 14:10:04.206 I/am_proc_died(949): [0,4838,de.php_tech.piggybudget]
04-10 14:10:04.207 I/am_finish_activity(949): [0,221901470,112614,de.php_tech.piggybudget/.MainActivity,proc died without state saved]
04-10 14:10:04.213 I/sf_frame_dur(271): [de.php_tech.piggybudget/de.php_tech.piggybudget.MainActivity,23,5,5,0,4,7,1]

**Comment by pmiddend** [comment] 2019-06-17 07:51
Closing because of duplicate of #18

**Closed by pmiddend** 2019-06-17 07:51 UTC
Labels: bug
